//popups
export const SETCREATERECIPEPOPUP = "SETCREATERECIPEPOPUP";

//flags
export const SETCREATEEDITFLAG = "SETCREATEEDITFLAG";

//recipes
export const EDITSELECTEDRECIPE = "EDITSELECTEDRECIPE";
export const SETSELECTEDRECIPEDEFAULT = "SETSELECTEDRECIPEDEFAULT";
export const CREATERECIPE = "CREATERECIPE";
export const EDITRECIPE = "EDITRECIPE";
export const DELETERECIPE = "DELETERECIPE";
export const SETFAVOURITE = "SETFAVOURITE";

//login
export const SETLOGINEMAIL = "SETLOGINEMAIL";
export const SETLOGINPASSWORD = "SETLOGINPASSWORD";
export const SETTOKEN = "SETTOKEN";
export const DELETETOKEN = "DELETETOKEN";
export const SETLOGINFIELDSDEFAULT = "SETLOGINFIELDSDEFAULT";

//register
export const SETREGISTERFIRSTNAME = "SETREGISTERFIRSTNAME";
export const SETREGISTERLASTNAME = "SETREGISTERLASTNAME";
export const SETREGISTEREMAIL = "SETREGISTEREMAIL";
export const SETREGISTERPASSWORD = "SETREGISTERPASSWORD";
export const SETREGISTERFIELDSDEFAULT = "SETREGISTERFIELDSDEFAULT";
